export const main: string;
export const normal: string;
export const editing: string;
export const edit: string;
export const view: string;
export const toggle: string;
export const completed: string;
export const destroy: string;
export const toggleAll: string;
